env: standard
runtime: nodejs12
service: org
instance_class: F1

handlers:
  - url: /static
    static_dir: static

  - url: /(.*\.(json|ico|js))$
    static_files: \1
    upload: .*\.(json|ico|js)$

  - url: .*
    static_files: index.html
    upload: index.html
